# Generated by Django 5.0.3 on 2024-03-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('haslo', models.TextField(null=True)),
                ('login', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id_log_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('adres_ip', models.TextField(null=True)),
                ('login', models.TextField(null=True)),
                ('haslo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaneDziekanat',
            fields=[
                ('numer_albumu', models.IntegerField(primary_key=True, serialize=False)),
                ('ocena_koncowa', models.FloatField(null=True)),
                ('imie', models.TextField(null=True)),
                ('nazwisko', models.TextField(null=True)),
                ('pesel', models.TextField(null=True)),
                ('srednia_ocen', models.FloatField(null=True)),
                ('id_przedmiot', models.IntegerField(null=True)),
                ('id_kierunku', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecyzjeStypendialne',
            fields=[
                ('id_decyzji', models.IntegerField(primary_key=True, serialize=False)),
                ('id_student', models.IntegerField(null=True)),
                ('decyzja', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formularz',
            fields=[
                ('id_formularza', models.IntegerField(primary_key=True, serialize=False)),
                ('typ_stypendium', models.TextField(null=True)),
                ('id_student', models.IntegerField(null=True)),
                ('data_zlozenia', models.DateField(null=True)),
                ('przychod_bez_podatku', models.FloatField(null=True)),
                ('srednia_ocen', models.FloatField(null=True)),
                ('dodatkowe_informacje', models.TextField(null=True)),
                ('plik_orzeczenie', models.CharField(max_length=45, null=True)),
                ('id_osiagniecia', models.IntegerField(null=True)),
                ('oswiadczenie_prawo_o_szkolnictwie', models.BooleanField(default=False)),
                ('oswiadczenie_gospodarstwo_domowe', models.BooleanField(default=False)),
                ('oswiadczenie_dochody', models.BooleanField(default=False)),
                ('zalacznik', models.TextField(null=True)),
                ('stopien_niepelnosprawnosci', models.TextField(null=True)),
                ('charakter_stopnia_niepelnosprawnosci', models.TextField(null=True)),
                ('data_rozpoczecia_orzeczenia', models.DateField(null=True)),
                ('data_konca_orzeczenia', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kierunek',
            fields=[
                ('id_kierunku', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_kierunku', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aktualnosci',
            fields=[
                ('id_aktualnosci', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_aktualnosci', models.TextField(null=True)),
                ('tekst_aktualnosci', models.TextField(null=True)),
                ('data_opublikowania', models.DateField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
        migrations.CreateModel(
            name='CzlonekRodziny',
            fields=[
                ('id_czlonka', models.IntegerField(primary_key=True, serialize=False)),
                ('imie_czlonka', models.TextField(null=True)),
                ('nazwisko_czlonka', models.TextField(null=True)),
                ('stopien_pokrewienstwa', models.IntegerField(null=True)),
                ('data_urodzenia', models.DateTimeField(null=True)),
                ('miejsce_pracy', models.TextField(null=True)),
                ('formularz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formularz')),
            ],
        ),
        migrations.CreateModel(
            name='InformacjeStypendialne',
            fields=[
                ('id_wersja', models.IntegerField(primary_key=True, serialize=False)),
                ('tekst', models.TextField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Konkursy',
            fields=[
                ('id_konkursu', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_konkursu', models.TextField(null=True)),
                ('nazwa_kierunku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kierunek')),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id_kontakt', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(null=True)),
                ('numer_tel', models.IntegerField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Kryteria',
            fields=[
                ('rok_kryterium', models.IntegerField(primary_key=True, serialize=False)),
                ('srednia_ocen', models.FloatField(null=True)),
                ('przychod_bez_podatku', models.FloatField(null=True)),
                ('id_kierunku', models.IntegerField(null=True)),
                ('id_formularza', models.IntegerField(null=True)),
                ('wzor_stypendium', models.TextField(null=True)),
                ('formularz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formularz')),
            ],
        ),
        migrations.CreateModel(
            name='KryteriaStrona',
            fields=[
                ('id_wersja', models.IntegerField(primary_key=True, serialize=False)),
                ('rok', models.TextField(null=True)),
                ('tekst', models.TextField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id_przedmiot', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_przedmiotu', models.TextField(null=True)),
                ('id_kierunku', models.IntegerField(null=True)),
                ('semestr', models.IntegerField(null=True)),
                ('punkty_ects', models.IntegerField(null=True)),
                ('kierunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kierunek')),
            ],
        ),
        migrations.CreateModel(
            name='OcenaKoncowaDziekanat',
            fields=[
                ('id_ocena', models.IntegerField(primary_key=True, serialize=False)),
                ('numer_albumu', models.IntegerField(null=True)),
                ('ocena_koncowa', models.FloatField(null=True)),
                ('id_przedmiotu', models.IntegerField(null=True)),
                ('dane_dziekanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.danedziekanat')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.przedmiot')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_uzytkownika', models.TextField(null=True)),
                ('haslo', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('data_rejestracji', models.DateField(null=True)),
                ('ikonka', models.TextField(null=True)),
                ('pesel', models.TextField(null=True)),
                ('imie', models.TextField(null=True)),
                ('nazwisko', models.TextField(null=True)),
                ('numer_telefonu', models.TextField(null=True)),
                ('nazwa_kierunku', models.TextField(null=True)),
                ('semestr', models.IntegerField(null=True)),
                ('numer_albumu', models.IntegerField(null=True)),
                ('rok_studiow', models.IntegerField(null=True)),
                ('numer_konta_bankowego', models.TextField(null=True)),
                ('decyzjeStypendialne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.decyzjestypendialne')),
                ('formularz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formularz')),
                ('kierunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kierunek')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('numer_albumu', models.IntegerField(primary_key=True, serialize=False)),
                ('punkty_rankingu', models.CharField(max_length=45, null=True)),
                ('typ_stypendium', models.CharField(max_length=65, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Powiadomienia',
            fields=[
                ('id_powiadomienia', models.IntegerField(primary_key=True, serialize=False)),
                ('tresc_powiadomienia', models.TextField(null=True)),
                ('naglowek_powiadomienia', models.TextField(null=True)),
                ('autor_powiadomienia', models.TextField(null=True)),
                ('student_id_powiadomienie', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Osiagniecia',
            fields=[
                ('id_osiagniecia', models.IntegerField(primary_key=True, serialize=False)),
                ('id_konkursu', models.IntegerField(null=True)),
                ('id_student', models.IntegerField(null=True)),
                ('punkty_osiagniecie', models.IntegerField(null=True)),
                ('typ_osiagniecia', models.TextField(null=True)),
                ('krotki_opis', models.TextField(null=True)),
                ('data_osiagniecia', models.DateField(null=True)),
                ('konkursy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.konkursy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='OcenaKoncowa',
            fields=[
                ('id_ocena', models.IntegerField(primary_key=True, serialize=False)),
                ('id_student', models.IntegerField(null=True)),
                ('ocena_koncowa', models.FloatField(null=True)),
                ('id_przedmiotu', models.IntegerField(null=True)),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.przedmiot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='danedziekanat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('adres_ip', models.CharField(max_length=45, null=True)),
                ('nazwa_uzytkownika', models.TextField(null=True)),
                ('haslo', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id_student', models.IntegerField(primary_key=True, serialize=False)),
                ('nowe_haslo', models.TextField(null=True)),
                ('nowy_numer_konta_bankowego', models.TextField(null=True)),
                ('nowy_email', models.TextField(null=True)),
                ('nowe_imie', models.TextField(null=True)),
                ('nowe_nazwisko', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
