# Generated by Django 5.0.3 on 2024-05-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaStatusow',
            fields=[
                ('id_statusu', models.AutoField(primary_key=True, serialize=False)),
                ('stary_status', models.CharField(max_length=20)),
                ('nowy_status', models.CharField(max_length=20)),
                ('data_zmiany', models.DateTimeField(null=True)),
                ('formularz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formularz')),
            ],
        ),
    ]
