# Generated by Django 5.0.3 on 2024-03-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='formularz',
        ),
    ]
