# Generated by Django 5.0.3 on 2024-06-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='status',
            field=models.CharField(blank=True, choices=[('nowe', 'Nowe'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone'), ('archiwalne', 'Archiwalne'), ('wszystkie', 'Wszystkie')], default='nowe', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HistoriaStatusow',
            fields=[
                ('id_historii', models.AutoField(primary_key=True, serialize=False)),
                ('stary_status', models.CharField(max_length=20)),
                ('nowy_status', models.CharField(max_length=20)),
                ('data_zmiany', models.DateTimeField(null=True)),
                ('data_zlozenia_form', models.DateTimeField(null=True)),
                ('formularz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formularz')),
            ],
        ),
    ]
