# Generated by Django 5.0.3 on 2024-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_nazwa_kierunku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='id_formularza',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
