# Generated by Django 5.0.3 on 2024-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historiastatusow'),
    ]

    operations = [
        migrations.AddField(
            model_name='kierunek',
            name='srednia_kierunku',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='status',
            field=models.CharField(blank=True, choices=[('nowe', 'Nowe'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone'), ('archiwalne', 'Archiwalne'), ('wszystkie', 'Wszystkie')], default='nowe', max_length=20, null=True),
        ),
    ]
