# Generated by Django 5.0.3 on 2024-03-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_formularz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ_Osiagniecia',
            fields=[
                ('id_typ_osiagniecia', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_typu', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminlog',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='danedziekanat',
            name='ocena_koncowa',
        ),
        migrations.RemoveField(
            model_name='powiadomienia',
            name='student_id_powiadomienie',
        ),
        migrations.RemoveField(
            model_name='studentlog',
            name='haslo',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='data_logowania',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='data_logowania',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='charakter_stopnia_niepelnosprawnosci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='data_konca_orzeczenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='data_rozpoczecia_orzeczenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='dodatkowe_informacje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='id_osiagniecia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='plik_orzeczenie',
            field=models.ImageField(blank=True, null=True, upload_to='dokumenty/orzeczenia'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='przychod_bez_podatku',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='stopien_niepelnosprawnosci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='zalacznik',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/zalaczniki'),
        ),
        migrations.AlterField(
            model_name='ustawienia',
            name='nowe_haslo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ustawienia',
            name='nowe_imie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ustawienia',
            name='nowe_nazwisko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ustawienia',
            name='nowy_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ustawienia',
            name='nowy_numer_konta_bankowego',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osiagniecia',
            name='typ_osiagniecia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typ_osiagniecia'),
        ),
    ]
