# Generated by Django 5.0.3 on 2024-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_typ_osiagniecia_remove_adminlog_haslo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='decyzjeStypendialne',
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='haslo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nazwa_uzytkownika',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='numer_albumu',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='numer_telefonu',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pesel',
            field=models.TextField(null=True, unique=True),
        ),
    ]
