# Generated by Django 5.0.3 on 2024-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_formularz_id_formularza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='id_czlonka',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
