# Generated by Django 5.0.3 on 2024-05-16 21:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_czlonekrodziny_id_czlonka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='komentarz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularz',
            name='punkty_osiagniecie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularz',
            name='status',
            field=models.CharField(blank=True, choices=[('nowe', 'Nowe'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='nowe', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='id_czlonka',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='imie_czlonka',
            field=models.TextField(null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='miejsce_pracy',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='nazwisko_czlonka',
            field=models.TextField(null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='stopien_pokrewienstwa',
            field=models.TextField(max_length=10, null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='student',
            name='imie',
            field=models.CharField(max_length=20, null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nazwisko',
            field=models.CharField(max_length=35, null=True, validators=[api.models.validate_string]),
        ),
    ]
