# Generated by Django 5.0.3 on 2024-06-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historiastatusow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rok_studiow',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semestr',
        ),
    ]
