# Generated by Django 5.0.3 on 2024-04-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_decyzjestypendialne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nazwa_kierunku',
        ),
        migrations.AddField(
            model_name='student',
            name='zalaczniki',
            field=models.FileField(null=True, upload_to='dokumenty/zalaczniki'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='ikonka',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='dokumenty/ikonki'),
        ),
        migrations.AlterField(
            model_name='student',
            name='imie',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nazwa_uzytkownika',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nazwisko',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='numer_konta_bankowego',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='numer_telefonu',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pesel',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
