# Generated by Django 5.0.3 on 2024-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_rok_studiow_remove_student_semestr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
