# Generated by Django 5.0.3 on 2024-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_nazwa_kierunku_student_zalaczniki_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='haslo',
        ),
        migrations.AlterField(
            model_name='student',
            name='zalaczniki',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/zalaczniki'),
        ),
    ]
