# Generated by Django 5.0.3 on 2024-05-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_formularz_komentarz_formularz_punkty_osiagniecie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osiagniecia',
            name='id_osiagniecia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
