# Generated by Django 5.0.3 on 2024-05-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_czlonekrodziny_formularz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czlonekrodziny',
            name='formularz_id',
        ),
    ]
