# Generated by Django 5.0.3 on 2024-06-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_osiagniecia_formularz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='id_czlonka',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
