# Generated by Django 5.0.3 on 2024-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_haslo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolNiepelnosprawnosci',
            fields=[
                ('id_symbolu', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa_symbolu', models.TextField(null=True)),
            ],
        ),
    ]
