# Generated by Django 5.0.3 on 2024-06-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_czlonekrodziny_id_czlonka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='id_kontakt',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
