# Generated by Django 5.0.3 on 2024-04-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_symbolniepelnosprawnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='symbol_niepelnosprawnosci',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.symbolniepelnosprawnosci'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symbolniepelnosprawnosci',
            name='nazwa_symbolu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
