# Generated by Django 5.0.3 on 2024-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_formularz_symbol_niepelnosprawnosci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='aktualny_semestr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularz',
            name='semestr_studenta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularz',
            name='zalacznik_niepelnosprawnosc',
            field=models.FileField(blank=True, null=True, upload_to='dokumenty/zalaczniki_niepelnosprawnosci'),
        ),
    ]
