# Generated by Django 5.0.3 on 2024-05-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_historiastatusuformularza'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historiastatusuformularza',
            table=None,
        ),
    ]
