# Generated by Django 5.0.3 on 2024-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_historiastatusuformularza_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='id_aktualnosci',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='ikonka',
            field=models.ImageField(blank=True, default='default.jpg', max_length=180, null=True, upload_to='dokumenty/ikonki'),
        ),
    ]
