# Generated by Django 5.0.3 on 2024-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_formularz_stopien_niepelnosprawnosci'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktualnySemestr',
            fields=[
                ('id_semestru', models.IntegerField(primary_key=True, serialize=False)),
                ('semestr', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemestrStudenta',
            fields=[
                ('id_semestru', models.IntegerField(primary_key=True, serialize=False)),
                ('semestr', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='haslo',
        ),
        migrations.AlterField(
            model_name='formularz',
            name='charakter_stopnia_niepelnosprawnosci',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='data_zlozenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='id_student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='srednia_ocen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='typ_stypendium',
            field=models.TextField(blank=True, null=True),
        ),
    ]
