# Generated by Django 5.0.3 on 2024-04-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aktualnysemestr_semestrstudenta_remove_student_haslo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='aktualny_semestr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.aktualnysemestr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularz',
            name='semestr_studenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.semestrstudenta'),
            preserve_default=False,
        ),
    ]
