# Generated by Django 5.0.3 on 2024-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kierunek',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
