# Generated by Django 5.0.3 on 2024-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_kierunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nazwa_uzytkownika',
        ),
    ]
