# Generated by Django 5.0.3 on 2024-04-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_student_nazwa_kierunku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nazwa_kierunku',
        ),
    ]
