# Generated by Django 5.0.3 on 2024-04-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_student_nazwa_kierunku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='kierunek',
        ),
        migrations.AlterField(
            model_name='student',
            name='nazwa_kierunku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kierunek'),
        ),
    ]
