# Generated by Django 5.0.3 on 2024-05-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_student_nazwa_kierunku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osiagniecia',
            name='konkursy',
        ),
        migrations.AddField(
            model_name='osiagniecia',
            name='liczba_osiagniec',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='typ_osiagniecia',
            name='punkty_osiagniecie',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Konkursy',
        ),
    ]
