# Generated by Django 5.0.3 on 2024-05-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_osiagniecia_id_konkursu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osiagniecia',
            name='punkty_osiagniecie',
        ),
    ]
