# Generated by Django 5.0.3 on 2024-05-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_osiagniecia_punkty_osiagniecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osiagniecia',
            name='typ_osiagniecia',
        ),
        migrations.DeleteModel(
            name='Typ_Osiagniecia',
        ),
    ]
