# Generated by Django 5.0.3 on 2024-05-05 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_osiagniecia_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osiagniecia',
            name='data_osiagniecia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osiagniecia',
            name='krotki_opis',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='osiagniecia',
            name='liczba_osiagniec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osiagniecia',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
