# Generated by Django 5.0.3 on 2024-05-07 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_osiagniecia_data_osiagniecia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
    ]
