# Generated by Django 5.0.3 on 2024-05-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_aktualnosci_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
    ]
