# Generated by Django 5.0.3 on 2024-05-08 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_formularz_stopien_niepelnosprawnosci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularz',
            name='id_student',
        ),
        migrations.AddField(
            model_name='formularz',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
