# Generated by Django 5.0.3 on 2024-05-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_czlonekrodziny_data_urodzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='stopien_niepelnosprawnosci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stopienniepelnosprawnosci'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='symbol_niepelnosprawnosci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.symbolniepelnosprawnosci'),
        ),
    ]
