# Generated by Django 5.0.3 on 2024-05-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_formularz_id_student_formularz_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czlonekrodziny',
            name='formularz',
        ),
        migrations.AddField(
            model_name='czlonekrodziny',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='stopien_pokrewienstwa',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='aktualny_semestr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aktualnysemestr'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='semestr_studenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.semestrstudenta'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='stopien_niepelnosprawnosci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stopienniepelnosprawnosci'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
