# Generated by Django 5.0.3 on 2024-05-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_czlonekrodziny_formularz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
    ]
