# Generated by Django 5.0.3 on 2024-05-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_formularz_stopien_niepelnosprawnosci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='aktualny_semestr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aktualnysemestr'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='semestr_studenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.semestrstudenta'),
        ),
    ]
