# Generated by Django 5.0.3 on 2024-05-13 18:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_kontakt_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='imie_czlonka',
            field=models.TextField(null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='miejsce_pracy',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='nazwisko_czlonka',
            field=models.TextField(null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='stopien_pokrewienstwa',
            field=models.TextField(max_length=10, null=True, validators=[api.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='przychod_bez_podatku',
            field=models.FloatField(blank=True, null=True, validators=[api.models.validate_digits_only]),
        ),
    ]
