# Generated by Django 5.0.3 on 2024-05-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_formularz_aktualny_semestr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='formularz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.formularz'),
        ),
    ]
