# Generated by Django 5.0.3 on 2024-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_czlonekrodziny_formularz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonekrodziny',
            name='stopien_pokrewienstwa',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
