# Generated by Django 5.0.3 on 2024-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_formularz_przychod_bez_podatku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='komentarz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularz',
            name='status',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='nowe', max_length=20),
        ),
    ]
