# Generated by Django 5.0.3 on 2024-05-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_czlonekrodziny_stopien_pokrewienstwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czlonekrodziny',
            name='formularz',
        ),
        migrations.AddField(
            model_name='czlonekrodziny',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
