# Generated by Django 5.0.3 on 2024-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_formularz_komentarz_formularz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='punkty_osiagniecie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
