# Generated by Django 5.0.3 on 2024-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_formularz_punkty_osiagniecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='status',
            field=models.CharField(blank=True, choices=[('nowe', 'Nowe'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='nowe', max_length=20, null=True),
        ),
    ]
