from django.contrib import admin
from .models import *

admin.site.register(Student)
admin.site.register(Kierunek)
admin.site.register(Formularz)
admin.site.register(DecyzjeStypendialne)
admin.site.register(Admin)
admin.site.register(Aktualnosci)
admin.site.register(Kontakt)
admin.site.register(Przedmiot)
admin.site.register(OcenaKoncowa)
admin.site.register(Kryteria)
admin.site.register(Ustawienia)
admin.site.register(Ranking)
admin.site.register(DaneDziekanat)
admin.site.register(Powiadomienia)
admin.site.register(KryteriaStrona)
admin.site.register(StudentLog)
admin.site.register(AdminLog)
admin.site.register(Konkursy)
admin.site.register(Osiagniecia)
admin.site.register(OcenaKoncowaDziekanat)
admin.site.register(CzlonekRodziny)
admin.site.register(SymbolNiepelnosprawnosci)
admin.site.register(StopienNiepelnosprawnosci)
# Register your models here.
